Repository Zach-Trani/markdown-editor, pull requests merged in 2023-02, with the labels that each got.

#8 Created Save Changes component
  package-lock.json
  package.json
  src/App.js
  src/Components/SaveChanges/index.js
Labels: enhancement

#11 feat: make save button orange
  package-lock.json
  package.json
  src/Components/SaveChanges/index.js
  src/Components/SaveChanges/save-changes.module.scss
Labels: enhancement

#16 fix: change site name and add favicon
  public/favicon.ico
  public/index.html
Labels: enhancement

#17 feat: create markdown component, include user input and a display for input
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/Components/Markdown/index.js
  src/index.css
  src/index.js
Labels: documentation, enhancement

#20 Markdown styling
  src/App.js
  src/Components/Markdown/index.js
  src/Components/Markdown/markdown.module.scss
  src/Components/NavBar/index.js
  src/Components/SaveChanges/index.js
Labels: enhancement

#28 Add syntax button component
  src/App.js
  src/Components/AddButton/index.js
  src/Components/Markdown/index.js
  src/Components/NavBar/index.js
  src/Components/SaveChanges/index.js
  src/Data/markDownSyntax.js
Labels: enhancement

#30 fix: Clean up documentation in components, remove unused references of content
  src/Components/AddButton/index.js
  src/Components/Markdown/index.js
  src/Components/NavBar/index.js
  src/Components/SaveChanges/index.js
  src/Data/markDownSyntax.js
Labels: documentation

#32 Add button style
  src/App.js
  src/Components/AddButton/index.js
  src/Components/Markdown/index.js
  src/Components/Markdown/markdown.module.scss
  src/Data/markDownSyntax.js
Labels: enhancement

#33 feat: add markdown text to localstorage and clear markdown with trash…
  src/Components/Markdown/index.js
  src/Components/NavBar/index.js
Labels: enhancement

#34 fix: add default text that doesnt persist page first trash click
  src/Components/Markdown/index.js
Labels: enhancement
